# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [22]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
array2  = np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([
                    [[1,2,3], [4,5,6]],
                    [[7,8,9], [10,11,12]],
                    [[13,14,15],[16,17,18]]
                    ])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.


In [23]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1.ndim, array1.dtype, array1.size, array1.shape, type(array1)

(1, dtype('int32'), 4, (4,), numpy.ndarray)

In [24]:
# Attributes of 2-dimensional array
array2.ndim, array2.dtype, array2.size, array2.shape, type(array2)

(2, dtype('int32'), 6, (2, 3), numpy.ndarray)

In [25]:
# Attributes of 3-dimensional array
array3.ndim, array3.dtype, array3.size, array3.shape, type(array3)

(3, dtype('int32'), 18, (3, 2, 3), numpy.ndarray)

In [27]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
array2_df = pd.DataFrame(array2)
array2_df

0  1  2
0  1  2  3
1  4  5  6

In [32]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [40]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
range_random_arr = np.random.randint(10,size=(7,2))
range_random_arr

array([[4, 9],
       [2, 7],
       [6, 7],
       [0, 7],
       [7, 5],
       [5, 0],
       [6, 3]])

In [42]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_arr = np.random.rand(3,5)
random_float_arr

array([[0.68434276, 0.61468473, 0.81689456, 0.26781774, 0.74090424],
       [0.21569399, 0.58776934, 0.94249816, 0.99750644, 0.68524799],
       [0.22135739, 0.21949916, 0.11930132, 0.99076458, 0.43639452]])

In [49]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [55]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random= np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random), random

(array([1, 2, 3, 4, 5, 6, 7, 9]),
 array([[7, 9, 3, 7, 1, 4, 4],
        [5, 7, 7, 4, 7, 3, 6],
        [2, 9, 5, 6, 4, 7, 9]]))

In [56]:
# Find the 0'th index of the latest array you created
random[0]

array([7, 9, 3, 7, 1, 4, 4])

In [57]:
# Get the first 2 rows of latest array you created
random[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [58]:
# Get the first 2 values of the first 2 rows of the latest array
random[:2,:2]

array([[7, 9],
       [5, 7]])

In [59]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random1 = np.random.randint(0,10,size =(3,5))
ones1 = np.ones((3,5))
random1, ones1

(array([[6, 0, 0, 8, 8],
        [3, 8, 2, 6, 5],
        [7, 8, 4, 0, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [60]:
# Add the two arrays together
random1 + ones1

array([[7., 1., 1., 9., 9.],
       [4., 9., 3., 7., 6.],
       [8., 9., 5., 1., 3.]])

In [61]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
# Try add the array of ones and the other most recent array together
ones1 + ones2.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [66]:
# Create another array of ones of shape (3, 5)
ones3= np.ones((3,5))
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
# Subtract the new array of ones from the other most recent array
ones1 - ones3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
# Multiply the ones array with the latest array
latest= random1 * ones1

In [73]:
# Take the latest array to the power of 2 using '**'
latest ** 2

array([[36.,  0.,  0., 64., 64.],
       [ 9., 64.,  4., 36., 25.],
       [49., 64., 16.,  0.,  4.]])

In [74]:
# Do the same thing with np.square()
np.square(latest)

array([[36.,  0.,  0., 64., 64.],
       [ 9., 64.,  4., 36., 25.],
       [49., 64., 16.,  0.,  4.]])

In [75]:
# Find the mean of the latest array using np.mean()
np.mean(latest)

4.466666666666667

In [76]:
# Find the maximum of the latest array using np.max()
np.max(latest)

8.0

In [77]:
# Find the minimum of the latest array using np.min()
np.min(latest)

0.0

In [78]:
# Find the standard deviation of the latest array
np.std(latest)

3.0081371127142607

In [79]:
# Find the variance of the latest array
np.var(latest)

9.04888888888889

In [84]:
# Reshape the latest array to (3, 5, 1)
reshape_latest= np.reshape(latest, (3,5,1))
reshape_latest

array([[[6.],
        [0.],
        [0.],
        [8.],
        [8.]],

       [[3.],
        [8.],
        [2.],
        [6.],
        [5.]],

       [[7.],
        [8.],
        [4.],
        [0.],
        [2.]]])

In [85]:
# Transpose the latest array
reshape_latest.T

array([[[6., 3., 7.],
        [0., 8., 8.],
        [0., 2., 4.],
        [8., 6., 0.],
        [8., 5., 2.]]])

What does the transpose do?

In [86]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0,10, size=(3,3))
arr2 = np.random.randint(0,10, size=(3,2))
arr1, arr2

(array([[9, 7, 5],
        [7, 8, 3],
        [0, 0, 9]]),
 array([[3, 6],
        [1, 2],
        [0, 4]]))

In [87]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[34, 88],
       [29, 70],
       [ 0, 36]])

In [89]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0,10,size=(4,3))
arr4 = np.random.randint(0,10,size=(4,3))

In [90]:
# Perform a dot product on the two newest arrays you created
# arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [92]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3.dot(arr4.T)

array([[28, 42, 49, 49],
       [13,  9,  7, 11],
       [65, 73, 72, 83],
       [18,  6,  0,  8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [93]:
# Compare the two arrays with '>'
arr3 >arr4

array([[False,  True, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [94]:
# Compare the two arrays with '>='
arr3 >= arr4

array([[False,  True, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [41]:
# Find which elements of the first array are greater than 7


In [95]:
# Which parts of each array are equal? (try using '==')
arr3 == arr4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [101]:
# Sort one of the arrays you just created in ascending order
arr4.sort()
arr4

array([[1, 4, 9],
       [3, 5, 6],
       [0, 6, 7],
       [4, 5, 7]])

In [102]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr4)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [103]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr4)

2

In [104]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr4)

6

In [109]:
arr3

array([[0, 7, 0],
       [0, 1, 1],
       [5, 6, 4],
       [0, 0, 2]])

In [108]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr3,axis=1)

array([1, 1, 1, 2], dtype=int64)

In [110]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr3, axis= 0)

array([0, 3, 0], dtype=int64)

In [117]:
# Create an array of normally distributed random numbers
np.random.normal(loc=0 , scale= 1 , size=(2,3))

array([[ 1.04386061,  0.52644816,  1.36388652],
       [ 2.53916272, -0.32449096, -0.20586672]])

In [119]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [120]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.